export const GET_ERRORS = 'GET_ERRORS';
export const SEND_VERIFY_TOKEN = 'SEND_VERIFY_TOKEN';
export const CURRENT_USER = 'CURRENT_USER';
export const NOT_VALIDATED = 'NOT_VALIDATED';
export const VALIDATED = 'VALIDATED';
export const USER_ACCOUNTS = 'USER_ACCOUNTS';
export const USER_SPECIFIC_ACCOUNT = 'USER_SPECIFIC_ACCOUNT';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
